version: "3.8"

services:
  app:
    build: .
    container_name: Mirbekov_KM
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python task_1/crud_script.py
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: products
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
